// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  article_quote: defineAsyncComponent(() => import("./ArticleQuote/index.vue")),
  articulo_parrafo: defineAsyncComponent(
    () => import("./ArticuloParrafo/index.vue")
  ),
  formulario: defineAsyncComponent(() => import("./Formulario/index.vue")),
  imagen: defineAsyncComponent(() => import("./Imagen/index.vue")),
  list_bullets: defineAsyncComponent(() => import("./ListBullets/index.vue")),
  subtitulo: defineAsyncComponent(() => import("./Subtitulo/index.vue")),
  titulos: defineAsyncComponent(() => import("./Titulos/index.vue")),
});
